# BestRAG 配置文件

retrieval:
  embedding_api_url: "http://127.0.0.1:8001/embed"
  embedding_dim: 1024
  vectorstore_type: "milvus"
  milvus_host: "127.0.0.1"
  milvus_port: 19530
  milvus_collection_prefix: "bestrag"
  rerank_api_url: "http://127.0.0.1:8002/rerank"
  top_k: 10

generation:
  api_key: "sk-52cb1d6686f94c809e8c51d0d7b2df8a"
  base_url: "https://api.deepseek.com/v1"
  model_name: "deepseek-chat"
